// Generated by https://quicktype.io

export interface FincasUser {
    code:   number;
    status: string;
    fincas: Finca[];
}

export interface Finca {
    id:                      number;
    user_id:                 number;
    nombre:                  string;
    id_municipio:            number;
    direccion:               string;
    altura_nivel_mar:        number;
    temperatura_centigrados: number;
    created_at:              string;
    updated_at:              string;
}
