// Generated by https://quicktype.io

export interface AlevinosDespachadosResponse {
    code:        number;
    status:      string;
    despachados: DespachadoAlevinos[];
}

export interface DespachadoAlevinos {
    id:                        number;
    fecha_salida:              string;
    nombre:                    string;
    municipio:                 string;
    departamento:              string;
    direccion:                 string;
    remision_numero:           string;
    lote_alevinos:             string;
    id_lote_numero:            number;
    numero_lote:               string;
    tamanio:                   number;
    edad_tcu:                  number;
    ovas_ml:                   number;
    fecha_incubacion:          string;
    fecha_fin_absorcion:       string;
    fecha_eclosion:            string;
    fecha_primer_alimento:     string;
    temp_eclosion:             number;
    referencia_alimento:       string;
    tratamientos_veterinarios: string;
    duracion_tratamiento:      number;
    temp_cargue:               number;
    conductor:                 number;
    NombreConductor:           string;
    tipo:                      string;
    es_talla:                  number;
    es_peso:                   number;
    cantidad:                  number;
    id_despacho:               number;
    talla:                     number;
    peso:                      number;
    semana:                    number;
    dia:                       string;
    despachado:                number;
    cantidad_alevinos:         number;
    talla_promedio:            number;
    peso_promedio:             number;
}
