// Generated by https://quicktype.io

export interface ConteoTrazabilidadResponse {
    code:               number;
    status:             string;
    ConteoTrazabilidad: ConteoTrazabilidad[];
    metodoConteo:       MetodoConteo[];
}

export interface ConteoTrazabilidad {
    id:                   number;
    remision:             string;
    total_ovas_enviadas:  number;
    tiene_reporte_conteo: number;
    cantidad_reportada:   number;
}

export interface MetodoConteo {
    id:          number;
    Nombre:      string;
    descripcion: string;
    esOvacon:    number;
    esOtro:      number;
}
