// Generated by https://quicktype.io

export interface DespachoResponse {
    code:            number;
    status:          string;
    despachos:       Despacho[];
    imagenes:        ImagenesReporte[];

}

export interface Despacho {
    id:           number;
    fecha_salida: string;
    dias_retraso: string;
    estado_llegada: string;
    observaciones:  string;
    temperatura:    number;
    certificado:  string;

}

export interface ImagenesReporte{
    id:           number;
    id_despacho:  number;
    archivo:      string;
    tipo: string;
    imagen: string;
   
}
