// Generated by https://quicktype.io

export interface DespachoNewResponse {
    code:         number;
    status:       string;
    distribucion: DistribucionNew[];
}

export interface DistribucionNew {
    trazabilidad:           number;
    nombre:                 string;
    finca:                  string;
    total_pedido:           number;
    cantidad_enviada_traza: number;
    caja:                   string;
    bandeja:                string;
    cantidad:               number;
    ovas_ml:                number;
}


