// Generated by https://quicktype.io


export class Mortalidad {
    id:                       number;
    id_pedido:                number;
    id_finca:                 number;
    temp_bandeja_superior:    number;
    temp_bandeja_intermedia:  number;
    temp_bandeja_inferior:    number;
    hielo_bandeja_superior:   number;
    hielo_bandeja_intermedia: number;
    hielo_bandeja_inferior:   number;
    preguntas:                Pregunta[];
    diario:                   Diario[];
}

export class Diario {
    id:            number;
    id_mortalidad: number;
    dia:           number;
    cantidad:      number;

}

export class Pregunta {
    id:            number;
    id_mortalidad: number;
    tipo_pregunta: string;
    pregunta:      string;
    respuesta:     string;
    observaciones: string;

}

export class Preguntas{

    tipo_pregunta: string;
    pregunta:      string;
    respuesta:     string;
    select?:       boolean 
    type:          string;
    data?:          any[]
    preguntas: Preguntas[];

}
