// Generated by https://quicktype.io


export class Mortalidad {
    constructor(){

     
        this.temp_ovas_llegar= 0         
        this.temp_agua_incubacion= 0     
        this.metodo_aclimatacion= ""      
        this.fuente_agua_incubacion=""   
        this.origen_agua_incubacion=""   
        this.uso_agua_incubacion=""      
        this.nivel_oxigeno=""            
        this.hora_aclimatacion=""        
        this.minutos_aclimatacion=""     
       
    
    }
    id:                       number;
    id_pedido:                number;
    id_finca:                 number;
    temp_bandeja_superior:    number;
    temp_bandeja_intermedia:  number;
    temp_bandeja_inferior:    number;
    hielo_bandeja_superior:   string;
    hielo_bandeja_intermedia: string;
    hielo_bandeja_inferior:   string;
    temp_ovas_llegar:         number;
    temp_agua_incubacion:     number;
    metodo_aclimatacion:      string;
    fuente_agua_incubacion:   string;
    origen_agua_incubacion:   string;
    uso_agua_incubacion:      string;
    nivel_oxigeno:            string;
    hora_aclimatacion:        string;
    minutos_aclimatacion:     string;
   
    preguntas:                Pregunta[];
    diario:                   Diario[];
}

export class Diario {
    id:            number;
    id_mortalidad: number;
    dia:           number;
    cantidad:      number;

}

export class Pregunta {
    id:            number;
    id_mortalidad: number;
    tipo_pregunta: string;
    pregunta:      string;
    respuesta:     string;
    observaciones: string;

}

export class Preguntas{

    tipo_pregunta: string;
    pregunta:      string;
    respuesta:     string;
    select?:       boolean 
    type:          string;
    data?:          any[]
    preguntas: Preguntas[];

}
