// Generated by https://quicktype.io

export interface ReportadoMortalidad {
    code:       number;
    status:     string;
    Reportados: Reportado[];
}

export interface Reportado {
    id:                       number;
    pedido:                   number; // total
    porcentaje:               number; // porcentaje
    adicional:                number; // adicional
    reposicion:               number; // repo
    total:                    number; // total
    cantidadReportada:        number;  
    PorcentajeMortalidad:     string;  
    nombre:                   string;
    municipio:                string;
    departamento:             string;

    Estado:                   string;  // aprobado rechazado. pendiente
    aprobado_Troutlodge:      number;  
    aprobado_Surala:          number;

    Observaciones:            string;
    demora_llegada:           boolean;
    danio_cajas:              boolean;
    temp_ovas_llegar:         number;
    temp_agua_incubacion:     number;
    llegada_ovas:             string;
    inicio_eclosion:          string;
    fin_eclosion:             string;
    fecha_inicioProblema:     string;
    fechaDespacho:            string,     
    created_at:               string;
    updated_at:               string;

}
