// Generated by https://quicktype.io


export class Mortalidad {
    constructor(){


     
       
    
    }
    id:                       number;
    id_pedido:                number;
    id_finca:                 number;
    temp_bandeja_superior:    number;
    temp_bandeja_intermedia:  number;
    temp_bandeja_inferior:    number;
    hielo_bandeja_superior:   string;
    hielo_bandeja_intermedia: string;
    hielo_bandeja_inferior:   string;

    utilizo_transporte:       boolean;  
    demora_llegada:           boolean;  
    danio_cajas:              boolean;  

    cambioGranja:             boolean;
    distintas:                boolean;
    similar:                  boolean;





    temp_ovas_llegar:         number;
    temp_agua_incubacion:     number;
    metodo_aclimatacion:      string;
    fuente_agua_incubacion:   string;
    origen_agua_incubacion:   string;
    uso_agua_incubacion:      string;
    nivel_oxigeno:            string;
    hora_aclimatacion:        string;
    minutos_aclimatacion:     string;

    //fechas que quedaran guardaddas como horas?
    llegada_ovas:             string;
    llegada_ovas_finca:       string;
    apertura_cajas:           string;
    inicio_hidratacion:       string;
    inicio_siembra:           string;
    finalizacion_siembra:     string;
    inicio_eclosion:          string;
    fin_eclosion:             string;
    fecha_inicioProblema:     string;  





   
    preguntas:                Pregunta[];
    diario:                   Diario[];
}

export class Diario {
    id:            number;
    id_mortalidad: number;
    dia:           number;
    cantidad:      number;

}

export class Pregunta {
    id:            number;
    id_mortalidad: number;
    tipo_pregunta: string;
    pregunta:      string;
    respuesta:     string;
    observaciones: string;

}

export class Preguntas{

    tipo_pregunta: string;
    pregunta:      string;
    respuesta:     string;
    select?:       boolean 
    type:          string;
    data?:          any[]
    preguntas: Preguntas[];

}
