// Generated by https://quicktype.io

export interface EstadisticaResponse {
    code:   number;
    status: string;
    datos:  DatoEstadistica[];
}

export interface DatoEstadistica {
    fecha_salida:   string;
    linea_genetica: string;
    edad_tcu:       number;
    tamanio:        number;
}


export class Estadistica{
    constructor(value, name){
        this.value = value;
        this.name = name
    }
    name: string;
    value: number;
}


export class EstadisticaMulti{
    constructor(value, name){
        this.series = value;
        this.name = name
    }
    name: string;
    series: Estadistica[] ;
}