// Generated by https://quicktype.io

export interface DespachoResponseActual {
    code:           number;
    status:         string;
    despacho:       Despacho[];
    totalPedidos:   number;
    total:          number;
    totalUsado:     number;

}

export class Totales {
    constructor(){
        
    }
    totalPedidos:   number;
    total:          number;
    totalUsado:     number;
}
export interface Despacho {
    id:             number;
    fecha:          string;
    fecha_salida:   string;
    numero_factura: string;
    numero_ovas:    string;
    porcentaje:     string;
    Activo:         number;
    created_at:     string;
    updated_at:     string;
}
