// Generated by https://quicktype.io

import { SaveFile } from './pedidos/guardar.pdf.response';

export class DespachoResponseActual {
    constructor(){
        this.despacho =[]
    }
    code:           number;
    status:         string;
    despacho:       Despacho[];
    totalPedidos:   number;
    total:          number;
    totalUsado:     number;

}

export class Totales {
    constructor(){
        
    }
    totalPedidos:   number;
    total:          number;
    totalUsado:     number;
}
export class Despacho {
    id:             number;
    fecha:          string;
    fecha_salida:   string;
    numero_factura: string;
    numero_ovas:    string;
    porcentaje:     string;
    Activo:         number;
    created_at:     string;
    updated_at:     string;


    estado_llegada: string;
    dias_retraso:   number;
    temperatura:    number;
    observaciones:  string;
}


export class DespachoLlegada {
    id:             number;
    estado_llegada: string;
    dias_retraso:   number;
    temperatura:    number;
    Observaciones:  string;
    fotos:          SaveFile[]


}
