
// Generated by https://quicktype.io

export interface EstadisticaResponse {
    code:   number;
    status: string;
    Mes:    Me[];
}

export interface Me {
    name:  string;
    value: number;
}
