// Generated by https://quicktype.io

export interface InformesResponse {
    code:    number;
    status:  string;
    informe: InformeResp[];
}

export interface InformeResp {
    id:                     number;
    user_id:                number;
    finca_id:               number;
    fecha_visita:           string;
    observaciones:          string;
    informeTecnico:         string;
    archivo_pcr:            string;
    histopatologia:         string;
    laboratorioNutricional: string;
    created_at:             string;
    updated_at:             string;
    nombre:                 string;
    municipio:              string;
    departamento:           string;
    nombreUsuario:          string;
    numero_identificacion:  string;


}
