// Generated by https://quicktype.io
export interface FincaUserResponse {
  code: number;
  status: string;
  userFincas: UserFinca[];
}

export class UserFinca {
    constructor(){
        this.id = 0
    }
  numeroIdentificacion: string;
  nombre: string;
  id: number;
  nombreFinca: string;
  Ubicacion: string;
}