// Generated by https://quicktype.io

export interface MortalidadResponse {
    status:   string;
    code:     number;
    registros: Registro[];
}

export interface Registro {
    id:               number;
    fecha:            string;
    total_ovas:       number;
    numero_ovas:      number;
    ovas_regalo:      number;
    ovas_adicionales: number;
    ovas_reposicion:  number;
    cantidad:         string;
    porcentaje:       string;
}
